// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchCreatePostCategories = `-- name: BatchCreatePostCategories :exec
INSERT INTO post_categories (post_id, category_id)
SELECT unnest($1::uuid[]), unnest($2::uuid[])
`

type BatchCreatePostCategoriesParams struct {
	PostID     []pgtype.UUID `json:"post_id"`
	CategoryID []pgtype.UUID `json:"category_id"`
}

func (q *Queries) BatchCreatePostCategories(ctx context.Context, arg BatchCreatePostCategoriesParams) error {
	_, err := q.db.Exec(ctx, batchCreatePostCategories, arg.PostID, arg.CategoryID)
	return err
}

const getCategories = `-- name: GetCategories :many
SELECT id, name, slug, description, icon, created_at FROM categories ORDER BY name
`

func (q *Queries) GetCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Icon,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
