// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Comment struct {
	ID              pgtype.UUID        `json:"id"`
	PostID          pgtype.UUID        `json:"post_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ParentCommentID pgtype.UUID        `json:"parent_comment_id"`
	Body            string             `json:"body"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CommentLike struct {
	ID        pgtype.UUID `json:"id"`
	CommentID pgtype.UUID `json:"comment_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

type Post struct {
	ID          pgtype.UUID        `json:"id"`
	AuthorID    pgtype.UUID        `json:"author_id"`
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	Body        string             `json:"body"`
	IsPublished bool               `json:"is_published"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PostCategory struct {
	PostID     pgtype.UUID `json:"post_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type PostLike struct {
	ID     pgtype.UUID `json:"id"`
	PostID pgtype.UUID `json:"post_id"`
	UserID pgtype.UUID `json:"user_id"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	GoogleID  string             `json:"google_id"`
	Username  pgtype.Text        `json:"username"`
	Email     string             `json:"email"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserFollow struct {
	FollowerID pgtype.UUID `json:"follower_id"`
	FolloweeID pgtype.UUID `json:"followee_id"`
}
