// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (title, body, slug, author_id, is_published)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, author_id, title, slug, body, is_published, created_at, updated_at
`

type CreatePostParams struct {
	Title       string      `json:"title"`
	Body        string      `json:"body"`
	Slug        string      `json:"slug"`
	AuthorID    pgtype.UUID `json:"author_id"`
	IsPublished bool        `json:"is_published"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Title,
		arg.Body,
		arg.Slug,
		arg.AuthorID,
		arg.IsPublished,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPostLike = `-- name: CreatePostLike :one
INSERT INTO post_likes (post_id, user_id)
VALUES ($1, $2)
ON CONFLICT (post_id, user_id) DO NOTHING
RETURNING id, post_id, user_id
`

type CreatePostLikeParams struct {
	PostID pgtype.UUID `json:"post_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreatePostLike(ctx context.Context, arg CreatePostLikeParams) (PostLike, error) {
	row := q.db.QueryRow(ctx, createPostLike, arg.PostID, arg.UserID)
	var i PostLike
	err := row.Scan(&i.ID, &i.PostID, &i.UserID)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const deletePostLike = `-- name: DeletePostLike :exec
DELETE FROM post_likes
WHERE post_id = $1 AND user_id = $2
`

type DeletePostLikeParams struct {
	PostID pgtype.UUID `json:"post_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeletePostLike(ctx context.Context, arg DeletePostLikeParams) error {
	_, err := q.db.Exec(ctx, deletePostLike, arg.PostID, arg.UserID)
	return err
}

const getCategoriesByPostIDs = `-- name: GetCategoriesByPostIDs :many
SELECT
    pc.post_id,
    c.id,
    c.name,
    c.slug,
    c.created_at
FROM post_categories pc
JOIN categories c ON c.id = pc.category_id
WHERE pc.post_id = ANY($1::uuid[])
`

type GetCategoriesByPostIDsRow struct {
	PostID    pgtype.UUID        `json:"post_id"`
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetCategoriesByPostIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetCategoriesByPostIDsRow, error) {
	rows, err := q.db.Query(ctx, getCategoriesByPostIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoriesByPostIDsRow
	for rows.Next() {
		var i GetCategoriesByPostIDsRow
		if err := rows.Scan(
			&i.PostID,
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentCountsByPostIDs = `-- name: GetCommentCountsByPostIDs :many
SELECT
    post_id,
    COUNT(*)::bigint AS comment_count
FROM comments
WHERE post_id = ANY($1::uuid[])
GROUP BY post_id
`

type GetCommentCountsByPostIDsRow struct {
	PostID       pgtype.UUID `json:"post_id"`
	CommentCount int64       `json:"comment_count"`
}

func (q *Queries) GetCommentCountsByPostIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetCommentCountsByPostIDsRow, error) {
	rows, err := q.db.Query(ctx, getCommentCountsByPostIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentCountsByPostIDsRow
	for rows.Next() {
		var i GetCommentCountsByPostIDsRow
		if err := rows.Scan(&i.PostID, &i.CommentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLikeCountsByPostIDs = `-- name: GetLikeCountsByPostIDs :many
SELECT
    post_id,
    COUNT(*)::bigint AS like_count
FROM post_likes
WHERE post_id = ANY($1::uuid[])
GROUP BY post_id
`

type GetLikeCountsByPostIDsRow struct {
	PostID    pgtype.UUID `json:"post_id"`
	LikeCount int64       `json:"like_count"`
}

func (q *Queries) GetLikeCountsByPostIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetLikeCountsByPostIDsRow, error) {
	rows, err := q.db.Query(ctx, getLikeCountsByPostIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLikeCountsByPostIDsRow
	for rows.Next() {
		var i GetLikeCountsByPostIDsRow
		if err := rows.Scan(&i.PostID, &i.LikeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, author_id, title, slug, body, is_published, created_at, updated_at
FROM posts
WHERE id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, id pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostBySearchAndCategoryPaginated = `-- name: GetPostBySearchAndCategoryPaginated :many
SELECT DISTINCT p.id, p.author_id, p.title, p.slug, p.body, p.is_published, p.created_at, p.updated_at
FROM posts p
LEFT JOIN post_categories pc ON pc.post_id = p.id
LEFT JOIN categories c ON c.id = pc.category_id
WHERE ($1::text IS NULL OR $1 = '' OR c.slug = $1)
AND ($2::text IS NULL OR $2 = '' OR p.title ILIKE '%' || $2 || '%')
ORDER BY p.created_at DESC
LIMIT $4 OFFSET $3
`

type GetPostBySearchAndCategoryPaginatedParams struct {
	CategorySlug pgtype.Text `json:"category_slug"`
	Search       pgtype.Text `json:"search"`
	Offset       int32       `json:"offset"`
	Limit        int32       `json:"limit"`
}

func (q *Queries) GetPostBySearchAndCategoryPaginated(ctx context.Context, arg GetPostBySearchAndCategoryPaginatedParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPostBySearchAndCategoryPaginated,
		arg.CategorySlug,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Body,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT id, author_id, title, slug, body, is_published, created_at, updated_at 
FROM posts 
WHERE slug = $1
`

func (q *Queries) GetPostBySlug(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRow(ctx, getPostBySlug, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostLike = `-- name: GetPostLike :one
SELECT id, post_id, user_id
FROM post_likes
WHERE post_id = $1 AND user_id = $2
`

type GetPostLikeParams struct {
	PostID pgtype.UUID `json:"post_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetPostLike(ctx context.Context, arg GetPostLikeParams) (PostLike, error) {
	row := q.db.QueryRow(ctx, getPostLike, arg.PostID, arg.UserID)
	var i PostLike
	err := row.Scan(&i.ID, &i.PostID, &i.UserID)
	return i, err
}

const getPostsByUsername = `-- name: GetPostsByUsername :many
SELECT p.id, p.author_id, p.title, p.slug, p.body, p.is_published, p.created_at, p.updated_at
FROM posts p
JOIN users u ON u.id = p.author_id
WHERE u.username = $1
ORDER BY p.created_at DESC
`

func (q *Queries) GetPostsByUsername(ctx context.Context, username pgtype.Text) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPostsByUsername, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Body,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsLikedByUsername = `-- name: GetPostsLikedByUsername :many
SELECT p.id, p.author_id, p.title, p.slug, p.body, p.is_published, p.created_at, p.updated_at
FROM post_likes pl
JOIN users u ON u.id = pl.user_id
JOIN posts p ON p.id = pl.post_id
WHERE u.username = $1
ORDER BY p.created_at DESC
`

func (q *Queries) GetPostsLikedByUsername(ctx context.Context, username pgtype.Text) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPostsLikedByUsername, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Body,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserLikedPostIDs = `-- name: GetUserLikedPostIDs :many
SELECT post_id
FROM post_likes
WHERE user_id = $1
AND post_id = ANY($2::uuid[])
`

type GetUserLikedPostIDsParams struct {
	UserID  pgtype.UUID   `json:"user_id"`
	Column2 []pgtype.UUID `json:"column_2"`
}

func (q *Queries) GetUserLikedPostIDs(ctx context.Context, arg GetUserLikedPostIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getUserLikedPostIDs, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var post_id pgtype.UUID
		if err := rows.Scan(&post_id); err != nil {
			return nil, err
		}
		items = append(items, post_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET title = $2, body = $3, slug = $4, is_published = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, author_id, title, slug, body, is_published, created_at, updated_at
`

type UpdatePostParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Body        string      `json:"body"`
	Slug        string      `json:"slug"`
	IsPublished bool        `json:"is_published"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.Slug,
		arg.IsPublished,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
